name: yapadsou
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_indicator: ^1.0.6
  firebase_core: ^2.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
  fonts:
    - family: IntegralCF
      fonts:
        - asset: lib/assets/fonts/IntegralCF-Regular.otf
          weight: 500
        - asset: lib/assets/fonts/IntegralCF-RegularOblique.otf
          style: italic
          weight: 500
        - asset: lib/assets/fonts/IntegralCF-BoldOblique.otf
          style: italic
          weight: 700
        - asset: lib/assets/fonts/IntegralCF-Bold.otf
          weight: 700
        - asset: lib/assets/fonts/IntegralCF-ExtraBold.otf
          weight: 800
        - asset: lib/assets/fonts/IntegralCF-ExtraBoldOblique.otf
          style: italic
          weight: 800
        - asset: lib/assets/fonts/IntegralCF-Medium.otf
          weight: 600
        - asset: lib/assets/fonts/IntegralCF-MediumOblique.otf
          style: italic
          weight: 600
        - asset: lib/assets/fonts/IntegralCF-DemiBold.otf
          weight: 600
        - asset: lib/assets/fonts/IntegralCF-DemiBoldOblique.otf
          style: italic
          weight: 600
        - asset: lib/assets/fonts/IntegralCF-Heavy.otf
          weight: 800
        - asset: lib/assets/fonts/IntegralCF-HeavyOblique.otf
          style: italic
          weight: 800
    - family: inter
      fonts:
        - asset: lib/assets/fonts/inter-Regular.ttf
          weight: 500

