// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxT0eutfgZhgmLPvmLLfYFLJLVEnqRxO0',
    appId: '1:754413701461:web:e0ff7b81918ea2e96947dc',
    messagingSenderId: '754413701461',
    projectId: 'yapasdsou-2710e',
    authDomain: 'yapasdsou-2710e.firebaseapp.com',
    storageBucket: 'yapasdsou-2710e.appspot.com',
    measurementId: 'G-3ML82VTMZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzssps8D6FhhQEaTS0uFyvs9kETJBGAIM',
    appId: '1:754413701461:android:3238e445252a83266947dc',
    messagingSenderId: '754413701461',
    projectId: 'yapasdsou-2710e',
    storageBucket: 'yapasdsou-2710e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGvPnQA7g-HI3yRyqtIL-TTYlCwiNSCYk',
    appId: '1:754413701461:ios:c802d626cb97d0b36947dc',
    messagingSenderId: '754413701461',
    projectId: 'yapasdsou-2710e',
    storageBucket: 'yapasdsou-2710e.appspot.com',
    iosClientId: '754413701461-flfvrjenken6qu3red3akejeca16f7mi.apps.googleusercontent.com',
    iosBundleId: 'com.example.yapadsou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGvPnQA7g-HI3yRyqtIL-TTYlCwiNSCYk',
    appId: '1:754413701461:ios:c802d626cb97d0b36947dc',
    messagingSenderId: '754413701461',
    projectId: 'yapasdsou-2710e',
    storageBucket: 'yapasdsou-2710e.appspot.com',
    iosClientId: '754413701461-flfvrjenken6qu3red3akejeca16f7mi.apps.googleusercontent.com',
    iosBundleId: 'com.example.yapadsou',
  );
}
